{
 "title": "Netology",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Утилизация CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(1-(irate(node_cpu_seconds_total{instance=\"node-exporter:9100\", mode=\"idle\"}[1m])))* 100",
     "legendFormat": "утилизация CPU (%)"
    }
   ]
  },
  {
   "title": "CPULA 1/5/15",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "node_load1", "legendFormat": "CPU LA 1" },
    { "expr": "node_load5", "legendFormat": "CPU LA 5" },
    { "expr": "node_load15", "legendFormat": "CPU LA 15" }
   ]
  },
  {
   "title": "Memory Free",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{instance=\"node-exporter:9100\"}",
     "legendFormat": "MemFree"
    }
   ]
  },
  {
   "title": "Количество места на файловой системе",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{instance=\"node-exporter:9100\", device=\"/dev/mapper/centos-root\"}",
     "legendFormat": "node_filesystem_avail_bytes"
    }
   ]
  }
 ]
}