filebeat.inputs:
- type: log
  # указываем, что логи мы будем брать из контейнеров
  paths:
    - '/var/lib/docker/containers/*/*.log'
  fields:
    type: docker
  fields_under_root: true

# добавляем процессор для обогащения логов лейблами
processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"

# указываем logstash на который нужно отправлять логи
output.logstash:
  hosts: ["logstash:5044"]
  loadbalance: false
  ssl.enabled: false
